### SEO, Analytics & 3rd-party
netlify_forms = false # add data-netlify attribute to contact and newsletter forms, false to disable Netlify forms
# gtm_id = '' # GTM tracking (leave blank to use GA)
disallow_search_engines = false # Disallow search engine crawling in robots.txt
# busuanzi
busuanzi = true # Enable busuanzi page views counter

### Content
favicon = true # Enable favicon, add your favicon files to /static/ directory
# avatar = 'avatar.png' # Custom avatar image in /assets/
grayscale_avatar = false # Add a grayscale filter to the avatar image
author = 'Zhen Huang' # Default author for <head> meta
description = "Personal blog and portfolio site of Zhen Huang 黄振的个人博客" # Add a global meta description to <head>
footer_text = "Built with [Hugo](https://gohugo.io/) & [Liftoff](https://github.com/wjh18/hugo-liftoff) modified by [Zhen Huang](https://github.com/ZhenHuangLab)." # Customize footer text
fallback_text = "No content available yet. Coming soon. 目前没有内容。" # Fallback text for empty content
label_drafts = false # Add a label indicator next to the title of any built drafts (dev only)

### Set announcement bar
AnnouncementBar = true
AnnouncementBarText = '''本站目前静态部署在Github，若图片或公式加载慢，请尝试刷新或魔法。'''

# Customize newsletter text
newsletter_header = "This is my custom newsletter header with a captivating title."
newsletter_description = "This is my custom newsletter description that tells you why you should sign up."
newsletter_submit = "Join now"
global_newsletter = false # Enable newsletter site-wide

# CSS / JavaScript
enable_postcss = false # Enable if you're using npm and want to utilize PostCSS processing
custom_css = 'custom.css' # Add the specified file to assets before setting this param to avoid errors
custom_js = 'custom.js' # Add the specified file to assets before setting this param to avoid errors
enableimgloop = true # Enable image loop in post

### Web schemas
# Open Graph
images = ['images/meta.jpg'] # Fallback for Open Graph and Twitter Cards images if none are present in front matter. Enter path to the image.
ogLocale = "en_US" # Open graph locale

# Twitter Cards
twitterSite = "ZhenVictorHuang" # Enter your twitter handle without the @
twitterCreator = "ZhenVictorHuang" # Enter your twitter handle without the @

# JSON-LD structured data schemas
schemaName = "Zhen Huang" # Enter your name
schemaLocale = "en-US" # Structured data locale
schemaImage = "images/default.png" # Image for Person structured data schema. Enter path to the image.
schemaImageWidth = 453 # Width of the above image
schemaImageHeight = 455 # Height of the above image

### Social
# Show social links in footer, home hero section, or about page
footer_socials = true
home_hero_socials = false
about_page_socials = false

# Enable or disable individual social icons
[social.links]
  # twitter = "username"
  github = "ZhenHuangLab"
  # stack_overflow = "userid/username" # include user id
  email = "zhen.victor.huang@gmail.com"
  bilibili = "37168500"
  # linkedin = "username" # Comment out to disable
  # mastodon_server = "example.social" # include subdomains if relevant, scheme not needed (defaults to https)
  # mastodon_user = "username" # don't include preceding @

# Enable or disable individual social share icons in posts
[social.share]
  facebook = true
  # linkedin = true
  twitter = false
  # reddit = true
  email = true